// <auto-generated />
using System;
using ApiUsuarios.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUsuarios.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230930190847_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUsuarios.Data.Entities.EscolaridadeEntity", b =>
                {
                    b.Property<int?>("IdEscolaridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdEscolaridade"));

                    b.Property<string>("Escolaridade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdEscolaridade");

                    b.ToTable("Escolaridade");
                });

            modelBuilder.Entity("ApiUsuarios.Data.Entities.UsuarioEntity", b =>
                {
                    b.Property<int?>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdUsuario"));

                    b.Property<DateTime?>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdEscolaridade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEscolaridade");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiUsuarios.Data.Entities.UsuarioEntity", b =>
                {
                    b.HasOne("ApiUsuarios.Data.Entities.EscolaridadeEntity", "Escolaridade")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEscolaridade")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Escolaridade");
                });

            modelBuilder.Entity("ApiUsuarios.Data.Entities.EscolaridadeEntity", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
